import type { Exercise, ExerciseVariant } from "../types/exercise";
import type { WorkoutLog } from "../types/log";
import type { Routine } from "../types/routine";

const now = new Date().toISOString();

export const seedExercises: Exercise[] = [
  {
    id: "ex-bench-press",
    name: "Bench Press",
    category: "Push",
    muscleGroups: ["chest", "triceps", "front-delts"],
    createdAt: now,
  },
  {
    id: "ex-incline-press",
    name: "Incline Press",
    category: "Push",
    muscleGroups: ["upper-chest", "triceps", "front-delts"],
    createdAt: now,
  },
  {
    id: "ex-lateral-raise",
    name: "Lateral Raise",
    category: "Push",
    muscleGroups: ["side-delts"],
    createdAt: now,
  },
  {
    id: "ex-triceps-pushdown",
    name: "Triceps Pushdown",
    category: "Push",
    muscleGroups: ["triceps"],
    createdAt: now,
  },
  {
    id: "ex-lat-pulldown",
    name: "Lat Pulldown",
    category: "Pull",
    muscleGroups: ["lats", "upper-back", "biceps"],
    createdAt: now,
  },
  {
    id: "ex-row",
    name: "Row",
    category: "Pull",
    muscleGroups: ["mid-back", "lats", "biceps"],
    createdAt: now,
  },
];

export const seedExerciseVariants: ExerciseVariant[] = [
  {
    id: "var-bench-barbell",
    exerciseId: "ex-bench-press",
    name: "Bench Press - Barbell",
    equipment: "barbell",
    gymLabel: "Flat bench",
    isActive: true,
    trackingType: "weight_reps",
    createdAt: now,
  },
  {
    id: "var-bench-smith",
    exerciseId: "ex-bench-press",
    name: "Bench Press - Smith",
    equipment: "smith",
    gymLabel: "Smith machine",
    isActive: true,
    trackingType: "weight_reps",
    createdAt: now,
  },
  {
    id: "var-incline-smith",
    exerciseId: "ex-incline-press",
    name: "Incline Press - Smith",
    equipment: "smith",
    gymLabel: "Incline smith",
    isActive: true,
    trackingType: "weight_reps",
    createdAt: now,
  },
  {
    id: "var-lateral-cable",
    exerciseId: "ex-lateral-raise",
    name: "Lateral Raise - Cable",
    equipment: "cable",
    gymLabel: "Cable station",
    isActive: true,
    trackingType: "weight_reps",
    createdAt: now,
  },
  {
    id: "var-pushdown-rope",
    exerciseId: "ex-triceps-pushdown",
    name: "Triceps Pushdown - Rope",
    equipment: "cable",
    gymLabel: "High pulley rope",
    isActive: true,
    trackingType: "weight_reps",
    createdAt: now,
  },
  {
    id: "var-lat-pulldown-wide",
    exerciseId: "ex-lat-pulldown",
    name: "Lat Pulldown - Wide Grip",
    equipment: "machine",
    gymLabel: "Lat pulldown machine",
    isActive: true,
    trackingType: "weight_reps",
    createdAt: now,
  },
  {
    id: "var-row-chest-supported",
    exerciseId: "ex-row",
    name: "Row - Chest Supported",
    equipment: "machine",
    gymLabel: "Chest supported row",
    isActive: true,
    trackingType: "weight_reps",
    createdAt: now,
  },
];

export const seedRoutines: Routine[] = [
  {
    id: "routine-push-a",
    name: "Push A",
    dayType: "Push",
    description: "Heavy push day",
    createdAt: now,
    updatedAt: now,
    exerciseRefs: [
      {
        id: "ref-push-a-1",
        routineId: "routine-push-a",
        exerciseId: "ex-bench-press",
        variantId: "var-bench-barbell",
        order: 1,
        prescription: {
          sets: 4,
          repRange: { min: 6, max: 8 },
          targetRIR: 1,
          restSeconds: 180,
          notes: "Main compound",
        },
      },
      {
        id: "ref-push-a-2",
        routineId: "routine-push-a",
        exerciseId: "ex-incline-press",
        variantId: "var-incline-smith",
        order: 2,
        prescription: {
          sets: 3,
          repRange: { min: 8, max: 12 },
          targetRIR: 1,
          restSeconds: 120,
        },
      },
      {
        id: "ref-push-a-3",
        routineId: "routine-push-a",
        exerciseId: "ex-lateral-raise",
        variantId: "var-lateral-cable",
        order: 3,
        prescription: {
          sets: 3,
          repRange: { min: 12, max: 15 },
          targetRIR: 1,
          restSeconds: 60,
        },
      },
      {
        id: "ref-push-a-4",
        routineId: "routine-push-a",
        exerciseId: "ex-triceps-pushdown",
        variantId: "var-pushdown-rope",
        order: 4,
        prescription: {
          sets: 3,
          repRange: { min: 10, max: 15 },
          targetRIR: 1,
          restSeconds: 60,
        },
      },
    ],
  },
  {
    id: "routine-push-b",
    name: "Push B",
    dayType: "Push",
    description: "Secondary push day",
    createdAt: now,
    updatedAt: now,
    exerciseRefs: [
      {
        id: "ref-push-b-1",
        routineId: "routine-push-b",
        exerciseId: "ex-bench-press",
        variantId: "var-bench-barbell",
        order: 1,
        prescription: {
          sets: 3,
          repRange: { min: 8, max: 10 },
          targetRIR: 1,
          restSeconds: 150,
        },
      },
      {
        id: "ref-push-b-2",
        routineId: "routine-push-b",
        exerciseId: "ex-lateral-raise",
        variantId: "var-lateral-cable",
        order: 2,
        prescription: {
          sets: 4,
          repRange: { min: 12, max: 15 },
          targetRIR: 1,
          restSeconds: 60,
        },
      },
      {
        id: "ref-push-b-3",
        routineId: "routine-push-b",
        exerciseId: "ex-triceps-pushdown",
        variantId: "var-pushdown-rope",
        order: 3,
        prescription: {
          sets: 3,
          repRange: { min: 12, max: 15 },
          targetRIR: 1,
          restSeconds: 60,
        },
      },
    ],
  },
];

export const seedWorkoutLogs: WorkoutLog[] = [
  {
    id: "log-1",
    date: "2026-03-01",
    routineId: "routine-push-a",
    exerciseId: "ex-bench-press",
    variantId: "var-bench-barbell",
    performedSets: [
      { reps: 8, weight: 25, rir: 1 },
      { reps: 7, weight: 25, rir: 1 },
      { reps: 6, weight: 25, rir: 2 },
      { reps: 6, weight: 25, rir: 2 },
    ],
    notes: "Solid but hard",
    createdAt: now,
  },
  {
    id: "log-2",
    date: "2026-03-03",
    routineId: "routine-push-a",
    exerciseId: "ex-incline-press",
    variantId: "var-incline-smith",
    performedSets: [
      { reps: 12, weight: 20, rir: 1 },
      { reps: 11, weight: 20, rir: 1 },
      { reps: 10, weight: 20, rir: 2 },
    ],
    createdAt: now,
  },
  {
    id: "log-3",
    date: "2026-03-05",
    routineId: "routine-push-b",
    exerciseId: "ex-bench-press",
    variantId: "var-bench-barbell",
    performedSets: [
      { reps: 10, weight: 25, rir: 1 },
      { reps: 9, weight: 25, rir: 1 },
      { reps: 8, weight: 25, rir: 2 },
    ],
    notes: "Could probably push 26 next time",
    createdAt: now,
  },
  {
    id: "log-4",
    date: "2026-03-06",
    routineId: "routine-push-b",
    exerciseId: "ex-lateral-raise",
    variantId: "var-lateral-cable",
    performedSets: [
      { reps: 15, weight: 7.5, rir: 1 },
      { reps: 14, weight: 7.5, rir: 1 },
      { reps: 13, weight: 7.5, rir: 1 },
      { reps: 12, weight: 7.5, rir: 2 },
    ],
    createdAt: now,
  },
];